### ISSUE TITLE
DB table name prefix does not match the plugin name

### ISSUE THREAD

**Issue by mudrd8mz** [m-schwabe/local_bs_badge_pool#1]
Same case as in https://github.com/m-schwabe/local_bs_badge_ladder/issues/1

**Comment by m-schwabe** [comment]
I have cut the "bs" part because of the limitation of the db table name to 28 characters. The table name "local_bs_badge_pool_categories" would be 30 characters long. I changed it now from "local_badge_pool_categories" to "local_bs_badge_pool_cat".

**Comment by mudrd8mz** [comment]
Yup. Thanks. Just please note that because there is no upgrade path, you may run into troubles on your sites that eventually used the previous version of the plugin already. I can confirm the new installations work well. This can be closed now I believe.
