### ISSUE TITLE
Missing sesskey check in managecat.php 

### ISSUE THREAD

**Issue by mudrd8mz** [m-schwabe/local_bs_badge_pool#2]
The script managecat.php is vulnerable to CSRF - https://docs.moodle.org/dev/Security:Cross-site_request_forgery

Before performing the `local_bs_badge_pool_delete_category()` call, `require_sesskey()` must be used and the sesskey must be part of the delete icon link.

**Comment by mudrd8mz** [comment]
Same applies to other places such as index.php?use=xx

**Comment by m-schwabe** [comment]
Thanks for that issue. I added the sesskey validations.
