### ISSUE TITLE
Unable to create the course badge from the template

### ISSUE THREAD

**Issue by mudrd8mz** [m-schwabe/local_bs_badge_pool#3]
Attempting to create a new course badge from a template in the pool ends with error:

```
Warning: fopen(/path/to/moodledata\temp\files\badgeicon_1448493851.tmp): failed to open stream: Permission denied in /local/bs_badge_pool/index.php on line 69

Warning: fwrite() expects parameter 1 to be resource, boolean given in /local/bs_badge_pool/index.php on line 70

Warning: fclose() expects parameter 1 to be resource, boolean given in /local/bs_badge_pool/index.php on line 71
```

**Comment by mudrd8mz** [comment]
I can see multiple issues here. The line

```
$a = file_encode_url($CFG->wwwroot.'/pluginfile.php', '/1/local_bs_badge_pool/badgepool/'.$usebadge.'/f3.png');
```

is highly suspicious and at least it has hard-coded context id that may not alway exist.

Using `file_get_contents()` with `http` streams is not recommended (or even allowed) in Moodle as many sites have it explicitly disabled. Plus it looks quite silly if Moodle reads the contents of its own file this way. You probably want to look at the method `stored_file::copy_content_to_temp()` and simply use that one.

The current code

```
$iconfile = $CFG->dataroot.'\temp\files\badgeicon_'.time().'.tmp';
```

does not work on Linux servers as far as I know. It is recommend to always use forward slashes in PHP, even on Windows. Additionally, there seems to be no code to make such that such a location exists. Please take a look at `make_request_directory()` if you really need things like this. That will make your live easier and your code cleaner.

**Comment by m-schwabe** [comment]
Thanks David for alterting me about this. I must confess that I tested this plugin only on a Windows machine. It is fixed now.
